# Generated by Django 5.0.2 on 2025-04-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('co2_emissions', models.FloatField()),
                ('delivery_efficiency', models.FloatField()),
                ('wage_fairness', models.FloatField()),
                ('human_rights_index', models.FloatField()),
                ('waste_management_score', models.FloatField()),
                ('ethical_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-ethical_score'],
            },
        ),
    ]
