# Generated by Django 5.0.2 on 2025-04-06 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('environmental_weight', models.FloatField(default=0.33)),
                ('social_weight', models.FloatField(default=0.33)),
                ('governance_weight', models.FloatField(default=0.34)),
                ('external_data_weight', models.FloatField(default=0.25)),
                ('co2_weight', models.FloatField(default=0.25)),
                ('water_usage_weight', models.FloatField(default=0.25)),
                ('energy_efficiency_weight', models.FloatField(default=0.25)),
                ('waste_management_weight', models.FloatField(default=0.25)),
                ('wage_fairness_weight', models.FloatField(default=0.25)),
                ('human_rights_weight', models.FloatField(default=0.25)),
                ('diversity_inclusion_weight', models.FloatField(default=0.25)),
                ('community_engagement_weight', models.FloatField(default=0.25)),
                ('transparency_weight', models.FloatField(default=0.5)),
                ('corruption_risk_weight', models.FloatField(default=0.5)),
                ('social_media_weight', models.FloatField(default=0.25)),
                ('news_coverage_weight', models.FloatField(default=0.25)),
                ('worker_reviews_weight', models.FloatField(default=0.25)),
                ('controversy_weight', models.FloatField(default=0.25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Controversy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('description', models.TextField()),
                ('resolution_status', models.CharField(choices=[('unresolved', 'Unresolved'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], max_length=20)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controversies', to='api.supplier')),
            ],
            options={
                'verbose_name_plural': 'Controversies',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MediaSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('sentiment_score', models.FloatField()),
                ('summary', models.TextField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_sentiments', to='api.supplier')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierESGReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('environmental_score', models.FloatField()),
                ('social_score', models.FloatField()),
                ('governance_score', models.FloatField()),
                ('summary', models.TextField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esg_reports', to='api.supplier')),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
    ]
