# Generated by Django 5.0.2 on 2025-04-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_supplier_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='industry',
        ),
        migrations.AddField(
            model_name='scoringweight',
            name='created_by',
            field=models.CharField(default='system', max_length=100),
        ),
        migrations.AddField(
            model_name='scoringweight',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoringweight',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='environmental_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='governance_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='risk_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='social_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
