# Generated by Django 5.0.2 on 2025-04-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_supplier_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='board_diversity',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='climate_risk',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='community_engagement',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='compliance_systems',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='corruption_risk',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='diversity_inclusion_score',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='energy_efficiency',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='ethics_program',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='geopolitical_risk',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='labor_dispute_risk',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='pollution_control',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='quality_control_score',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='renewable_energy_percent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_diversity',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='traceability',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='transparency_score',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='water_usage',
            field=models.FloatField(blank=True, default=50, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='worker_safety',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
    ]
