# Generated by Django 5.0.3 on 2025-04-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_supplier_board_diversity_supplier_climate_risk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='co2_emissions',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='delivery_efficiency',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='human_rights_index',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='wage_fairness',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='waste_management_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
